---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-pv-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 300Mi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: init-script
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 10Mi
---
apiVersion: v1
kind: Service
metadata:
  name: mongo
  labels:
    app: mongo
spec:
  ports:
    - port: 27017
  selector:
    app: mongo
  clusterIP: None
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo
  labels:
    app: mongo
spec:
  selector:
    matchLabels:
      app: mongo
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mongo
    spec:
      initContainers:
      - name: init-mongo
        image: appropriate/curl
        args:
          - "-o"
          - "/tmp/data/init-mongo.js"
          - "https://gist.githubusercontent.com/olivebay/d6eb1a17d2469630efd33d5d6af559fc/raw/f80c5b87d2d5cd3998f4dc109d34c522bde7cf62/init-mongo.js"
        volumeMounts:
        - name: init-script
          mountPath: /tmp/data
        resources:
          limits:
            memory: "50Mi"
            cpu: "50m"
          requests:
            memory: "50Mi"
            cpu: "50m"
      containers:
      - image: mongo:4.2.3
        name: mongo
        ports:
        - containerPort: 27017
          name: mongo
        env:
        - name: MONGO_INITDB_DATABASE
          value: "urls"
        readinessProbe:
          exec:
           command:
              - /bin/sh
              - -c
              - mongo --eval "db.adminCommand('ping')"
          periodSeconds: 5
        resources:
          limits:
            memory: "300Mi"
            cpu: "200m"
          requests:
            memory: "300Mi"
            cpu: "200m"
        volumeMounts:
        - name: mongo-persistent-storage
          mountPath: /data/db
        - name: init-script
          mountPath: /docker-entrypoint-initdb.d
      volumes:
      - name: init-script
        persistentVolumeClaim:
          claimName: init-script
      - name: mongo-persistent-storage
        persistentVolumeClaim:
          claimName: mongo-pv-claim
---
apiVersion: v1
kind: Service
metadata:
  name: apisvc
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 9090
    nodePort: 31000
  selector:
    app: api
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: api
  name: api
spec:
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - image: melibou/urlinfo
        imagePullPolicy: Always
        name: api
        ports:
        - containerPort: 9090
          name: http
        env:
        - name: MONGO_DIAL
          value: "mongodb://mongo:27017"
        readinessProbe:
          httpGet:
            path: /healthz
            port: 9090
          initialDelaySeconds: 10
          periodSeconds: 3
        resources:
          limits:
            memory: "100Mi"
            cpu: "150m"
          requests:
            memory: "50Mi"
            cpu: "100m"
---
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: api-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: api
  minReplicas: 1
  maxReplicas: 4
  metrics:
  - type: Resource
    resource:
      name: memory
      target:
        averageUtilization: 60
        type: Utilization
  - type: Resource
    resource:
      name: cpu
      target:
        averageUtilization: 50
        type: Utilization